name: Release PR develop -> main

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog between main..develop
        id: changelog
        uses: metcalfc/changelog-generator@v4.6.2
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          head-ref: develop
          base-ref: main

      
      - name: Create or update PR develop -> main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ## Check, if the release PR exists

          PR_NUMBER=$(gh pr list \
            --base main \
            --head develop \
            --state open \
            --json number \
            --jq '.[0].number')

          if [ -n "$PR_NUMBER" ]; then
            echo "PR exists, let's update it"
            gh pr edit "$PR_NUMBER" --body "${{ steps.changelog.outputs.changelog }}"
          else
            ## Create new PR
            gh pr create \
              --base main \
              --head develop \
              --title "Release: develop -> main" \
              --body "${{ steps.changelog.outputs.changelog }}"
          fi
